apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
spec:
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      serviceAccountName: go-micro 
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: currency
          ports:
            - name: grpc
              containerPort: 7000
          env:
            - name: PORT
              value: "7000"
            - name: MICRO_REGISTRY
              value: "kubernetes"
            - name: TRACING_ENABLE
              value: "true"
            - name: TRACING_JAEGER_URL
              value: "http://jaeger-collector.default.svc.cluster.local:14268/api/traces"
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:7000"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:7000"]
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 64Mi
          #   limits:
          #     cpu: 200m
          #     memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: currency
spec:
  type: ClusterIP
  selector:
    app: currency
  ports:
    - name: grpc
      port: 7000
      targetPort: 7000
